# Site settings
title:          Logan Jordon
description:    "Glory to God Alone"
url:            "https://www.loganjordon.com"
non_posts:
  - '404'
  - 'About'
  - 'Archive'
  - 'Message Sent!'
  - 'Contact'
  - 'Subscribed!'

# Google Analytics (set up later)
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Logan Jordon
  url:          https://www.loganjordon.com
  email:        logan@loganjordon.com
  twitter:      https://twitter.com/LoganRJordon

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year/:month/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale